# Model Configuration
model_name: "Qwen/Qwen2-VL-7B-Instruct"  # Open-source Vision-Language Model
vision_layer: "visual.blocks.11"        # Target vision encoder layer
projector_layer: "visual.merger"        # Vision-language projector layer
transformer_layer: "model.layers.16"    # Target intermediate residual stream layer
device: "cuda"
dtype: "bfloat16"                       # float32, float16, bfloat16
use_flash_attention: true
adapter_type: "huggingface"             # "huggingface" or "mock"
